# Generated by Django 3.2.4 on 2021-06-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
